id: P51D218D5
initial_creation_type: input
source_metadata:
  title: Nyala Pema Dündul Series
  language: en
  description: 'Texts by and about the great siddha of Nyarong, Nyala Pema Dündul
    (nyag bla padma bdud ''dul, 1816–1872):'
  volume:
    62da5edfc9864760902b2c30aaea0c69:
      title: Advice Revealing How Our Faults Become Clear
      parent: Advice
    dcf09386a23d4a4c83cf4e8ffa579395:
      title: Advice on Abandoning the Eight Worldly Concerns
      parent: Advice
    0253395efe4d4548a46bcaec51297a07:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    d9726e534839474c973f1c9cd9d203a2:
      title: Signs that the Common Preliminary Practices Have Penetrated the Mind
      parent: Advice
    819e80de2b824de09120917070df9fae:
      title: Song of Advice for Giving Up Meat Eating
      parent: Advice
    68f847ecc7a541e4ba2f5af8811042ee:
      title: The Heaven of Solitude
      parent: Advice
    880c034f989a41b8af51cef47d3e2ff4:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Confession
    25ed50e934634022b52e8c8647c1d927:
      title: Dharmakāya Transference
      parent: Phowa
    78bbf1e8c9b1463a976bd5780bdb3b9c:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
created_at: '2022-03-01T01:03:40.615766'
last_modified_at: '2022-03-01T01:03:40.615772'
